language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update

install:
  - composer --working-dir=htdocs/xoops_lib/ install

before_script:
  - mysql -e 'create database xoops_test;'
  - php console/console.php ci-bootstrap
  - php console/console.php ci-install
  - php console/console.php install-module xmf
  - php console/console.php install-module avatars
  - php console/console.php install-module userrank
  - php console/console.php install-module page

script:
  - htdocs/xoops_lib/vendor/bin/phpunit --configuration tests/unit/testXoopsLib.xml --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
